### ISSUE TITLE
JOSS comment: CRAN

### ISSUE THREAD

**Issue by DominiqueMakowski** [ClaudioZandonella/PRDA#2]
Related to https://github.com/openjournals/joss-reviews/issues/2810 :

It seems like this package is not on CRAN. Is this correct? If so, I wonder why is that, it seems in pretty good shape to be uploaded?

**Comment by mmrabe** [comment]
There is a phrase in your manuscript stating that the package is available on CRAN with something looking like a dummy to be replaced with the actual link. So it seems like you're in the process of pushing to CRAN. I'm sure you're aware but please remember to replace the dummy or remove it from the manuscript if getting the package to CRAN is not feasible right now (which would be just fine).

**Comment by ClaudioZandonella** [comment]
Dear @DominiqueMakowski and @mmrabe, you are right the package is not yet on CRAN. I preferred to wait for the reviews so I could make the last changes and then send to CRAN.

If you agree with the solutions provided for all the issues, now I can merge everything in the master branch and send the package to CRAN. If accepted I will update the installation instructions in the documentation and in the paper.

**Comment by mmrabe** [comment]
You can always add references/citations to a CRAN package by uploading a new version but you won't be able to change a paper once it is published. And as far as I can tell, the package is a very suitable CRAN candidate already. So yes, I highly recommend submitting to CRAN soon so that you can include a CRAN reference in your manuscript.

**Comment by ClaudioZandonella** [comment]
Dear @mmrabe and @DominiqueMakowski I have just submitted the package to CRAN. It shouldn't take too long for the CRAN review process. As soon as they answer me I will update the last changes to the manuscript. Thanks!

**Comment by ClaudioZandonella** [comment]
Dear @mmrabe  and @DominiqueMakowski, I received only one note from CRAN reviewers.  They required to avoid modify the .GlobalEnv as this is not allowed by the CRAN policies. So I removed the seed argument from the functions and added external `set.seed()` in the examples and documentation to obtain reproducible results. See commit 6b4802cb9c0316aa1c05d831e161efe5d466a1a3 and 6cce235c139f8bba2537e8a61eb9d086be645511. I have already resubmitted the package to CRAN.

**Comment by ClaudioZandonella** [comment]
Dear @DominiqueMakowski and @mmrabe, now the package is available on CRAN! I have already updated all the info in the documentation and paper about downloading the package (commit 3570f7d9c2b51e6cb8839d0b1b02258e90fab5f5). So I can consider the issue closed. Thanks!
