### ISSUE TITLE
JOSS comment: Community guidelines

### ISSUE THREAD

**Issue by DominiqueMakowski** [ClaudioZandonella/PRDA#3]
Related to openjournals/joss-reviews#2810 :

I didn't find any community guidelines (https://github.com/ClaudioZandonella/PRDA/community), adding these could be good to guide potential contributors (in addition to the contributing section of the README).

**Comment by ClaudioZandonella** [comment]
Dear @DominiqueMakowski, 

I added the Community Guidelines and Code of Conduct as standalone files.

Changes are all in the develop branch I will merge everything at the end. Let me know if this is fine so I will close the issue👍

**Comment by DominiqueMakowski** [comment]
looks good
