### ISSUE TITLE
JOSS comment: auto effect_type

### ISSUE THREAD

**Issue by DominiqueMakowski** [ClaudioZandonella/PRDA#5]
Related to openjournals/joss-reviews#2810 :

Currently, if let's say `effect_type` arg is left to default ("correlation") and we change the `test_method` to that of a mean difference test, it errors. However, I wonder whether it would be simpler to just have the effect_type adjust automatically based on the input of test_method, especially in straightforward cases like correlations and t-tests?

**Comment by ClaudioZandonella** [comment]
Dear @DominiqueMakowski thanks for pointing out this issue. Initially, we wanted to be sure that the user was aware of the effect type considered; so it was required to specify both the effect_type and test_method argument. However, we agree that this is redundant and most of the times it ends up with annoying error messages.  Now, following your suggestion, we let the effect type to be set automatically and the user is required to define only the test method.
At the moment the changes are in the develop branch. We will merge everything in the master branch after the review process.
