### ISSUE TITLE
JOSS comment: docstrings

### ISSUE THREAD

**Issue by DominiqueMakowski** [ClaudioZandonella/PRDA#6]
Related to openjournals/joss-reviews#2810 :

In the API documentation of the `sample_n2` argument, I would add the cases where this argument applies (e.g., "This argument is used when 'test_method' is ...").

**Comment by ClaudioZandonella** [comment]
Dear @DominiqueMakowski, we specified when arguments are required in the functions documentation. This made the functions help page much more clear. Thanks for the suggestion.
