### ISSUE TITLE
JOSS comment: Future plans

### ISSUE THREAD

**Issue by DominiqueMakowski** [ClaudioZandonella/PRDA#7]
Related to openjournals/joss-reviews#2810 :

Maybe add a "Future plans" or a section like that (if applicable) so that one can see the direction of this package's future development, and eventually know where/how to contribute.

**Comment by ClaudioZandonella** [comment]
Dear @DominiqueMakowski,  good suggestion! I added a Future Plans list in the Read me and in the Community Guidelines.

Currently, there are only two points but it will be useful in the future to collect other suggestions for new features as well.

Changes are all in the develop branch I will merge everything at the end. Let me know if this is fine so I will close the issue👍

**Comment by DominiqueMakowski** [comment]
looks good
